// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: promotion.proto

package protos

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @Created 13/10/2021
// @Updated 26/10/2021
type Promotion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created     string `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated     string `protobuf:"bytes,3,opt,name=updated,proto3" json:"updated,omitempty"`
	Code        string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Sku         string `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty         uint32 `protobuf:"varint,6,opt,name=qty,proto3" json:"qty,omitempty"`
	Freebies    string `protobuf:"bytes,7,opt,name=freebies,proto3" json:"freebies,omitempty"`
	FreebiesQty uint32 `protobuf:"varint,8,opt,name=freebiesQty,proto3" json:"freebiesQty,omitempty"`
	Type        string `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Promotion) Reset() {
	*x = Promotion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Promotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promotion) ProtoMessage() {}

func (x *Promotion) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promotion.ProtoReflect.Descriptor instead.
func (*Promotion) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{0}
}

func (x *Promotion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Promotion) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Promotion) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *Promotion) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Promotion) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Promotion) GetQty() uint32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Promotion) GetFreebies() string {
	if x != nil {
		return x.Freebies
	}
	return ""
}

func (x *Promotion) GetFreebiesQty() uint32 {
	if x != nil {
		return x.FreebiesQty
	}
	return 0
}

func (x *Promotion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// @Created 13/10/2021
type CreatePromotionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Sku         string `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty         uint32 `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Freebies    string `protobuf:"bytes,4,opt,name=freebies,proto3" json:"freebies,omitempty"`
	FreebiesQty uint32 `protobuf:"varint,5,opt,name=freebiesQty,proto3" json:"freebiesQty,omitempty"`
	Type        string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CreatePromotionRequest) Reset() {
	*x = CreatePromotionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePromotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromotionRequest) ProtoMessage() {}

func (x *CreatePromotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromotionRequest.ProtoReflect.Descriptor instead.
func (*CreatePromotionRequest) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePromotionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePromotionRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreatePromotionRequest) GetQty() uint32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CreatePromotionRequest) GetFreebies() string {
	if x != nil {
		return x.Freebies
	}
	return ""
}

func (x *CreatePromotionRequest) GetFreebiesQty() uint32 {
	if x != nil {
		return x.FreebiesQty
	}
	return 0
}

func (x *CreatePromotionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// @Created 13/10/2021
// @Updated 18/10/2021
type CreatePromotionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Promotion *Promotion `protobuf:"bytes,1,opt,name=promotion,proto3" json:"promotion,omitempty"`
}

func (x *CreatePromotionResponse) Reset() {
	*x = CreatePromotionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePromotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromotionResponse) ProtoMessage() {}

func (x *CreatePromotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromotionResponse.ProtoReflect.Descriptor instead.
func (*CreatePromotionResponse) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePromotionResponse) GetPromotion() *Promotion {
	if x != nil {
		return x.Promotion
	}
	return nil
}

// @Created 13/10/2021
type GetAllPromotionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Promotions []*Promotion `protobuf:"bytes,1,rep,name=promotions,proto3" json:"promotions,omitempty"`
}

func (x *GetAllPromotionsResponse) Reset() {
	*x = GetAllPromotionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPromotionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPromotionsResponse) ProtoMessage() {}

func (x *GetAllPromotionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPromotionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPromotionsResponse) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllPromotionsResponse) GetPromotions() []*Promotion {
	if x != nil {
		return x.Promotions
	}
	return nil
}

// @Created 18/10/2021
type UpdatePromotionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Sku         string `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty         uint32 `protobuf:"varint,6,opt,name=qty,proto3" json:"qty,omitempty"`
	Freebies    string `protobuf:"bytes,7,opt,name=freebies,proto3" json:"freebies,omitempty"`
	FreebiesQty uint32 `protobuf:"varint,8,opt,name=freebiesQty,proto3" json:"freebiesQty,omitempty"`
	Type        string `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *UpdatePromotionRequest) Reset() {
	*x = UpdatePromotionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePromotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromotionRequest) ProtoMessage() {}

func (x *UpdatePromotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromotionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePromotionRequest) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePromotionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePromotionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePromotionRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *UpdatePromotionRequest) GetQty() uint32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *UpdatePromotionRequest) GetFreebies() string {
	if x != nil {
		return x.Freebies
	}
	return ""
}

func (x *UpdatePromotionRequest) GetFreebiesQty() uint32 {
	if x != nil {
		return x.FreebiesQty
	}
	return 0
}

func (x *UpdatePromotionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// @Created 18/10/2021
type UpdatePromotionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Promotion *Promotion `protobuf:"bytes,1,opt,name=promotion,proto3" json:"promotion,omitempty"`
}

func (x *UpdatePromotionResponse) Reset() {
	*x = UpdatePromotionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePromotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromotionResponse) ProtoMessage() {}

func (x *UpdatePromotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromotionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePromotionResponse) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePromotionResponse) GetPromotion() *Promotion {
	if x != nil {
		return x.Promotion
	}
	return nil
}

// @Created 13/10/2021
type DeletePromotionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePromotionRequest) Reset() {
	*x = DeletePromotionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePromotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromotionRequest) ProtoMessage() {}

func (x *DeletePromotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromotionRequest.ProtoReflect.Descriptor instead.
func (*DeletePromotionRequest) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePromotionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// @Created 13/10/2021
type DeletePromotionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePromotionResponse) Reset() {
	*x = DeletePromotionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePromotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromotionResponse) ProtoMessage() {}

func (x *DeletePromotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromotionResponse.ProtoReflect.Descriptor instead.
func (*DeletePromotionResponse) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePromotionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// @Created 13/10/2021
type CheckPromotionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku string `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty uint32 `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
}

func (x *CheckPromotionRequest) Reset() {
	*x = CheckPromotionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPromotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPromotionRequest) ProtoMessage() {}

func (x *CheckPromotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPromotionRequest.ProtoReflect.Descriptor instead.
func (*CheckPromotionRequest) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{8}
}

func (x *CheckPromotionRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CheckPromotionRequest) GetQty() uint32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

// @Created 13/10/2021
// @Updated 18/10/2021
type CheckPromotionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromotionType string `protobuf:"bytes,1,opt,name=promotionType,proto3" json:"promotionType,omitempty"`
	Freebies      string `protobuf:"bytes,2,opt,name=Freebies,proto3" json:"Freebies,omitempty"`
	Qty           uint32 `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
}

func (x *CheckPromotionResponse) Reset() {
	*x = CheckPromotionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPromotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPromotionResponse) ProtoMessage() {}

func (x *CheckPromotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPromotionResponse.ProtoReflect.Descriptor instead.
func (*CheckPromotionResponse) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{9}
}

func (x *CheckPromotionResponse) GetPromotionType() string {
	if x != nil {
		return x.PromotionType
	}
	return ""
}

func (x *CheckPromotionResponse) GetFreebies() string {
	if x != nil {
		return x.Freebies
	}
	return ""
}

func (x *CheckPromotionResponse) GetQty() uint32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

var File_promotion_proto protoreflect.FileDescriptor

var file_promotion_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9,
	0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x65, 0x65,
	0x62, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x65, 0x65,
	0x62, 0x69, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x72, 0x65, 0x65, 0x62, 0x69, 0x65, 0x73,
	0x51, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x66, 0x72, 0x65, 0x65, 0x62,
	0x69, 0x65, 0x73, 0x51, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x72, 0x65, 0x65, 0x62, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x72, 0x65, 0x65, 0x62, 0x69, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x72, 0x65,
	0x65, 0x62, 0x69, 0x65, 0x73, 0x51, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x66, 0x72, 0x65, 0x65, 0x62, 0x69, 0x65, 0x73, 0x51, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x43, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x70, 0x72,
	0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xb2, 0x01, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x6b, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10, 0x0a,
	0x03, 0x71, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x72, 0x65, 0x65, 0x62, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x72, 0x65, 0x65, 0x62, 0x69, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x66,
	0x72, 0x65, 0x65, 0x62, 0x69, 0x65, 0x73, 0x51, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x66, 0x72, 0x65, 0x65, 0x62, 0x69, 0x65, 0x73, 0x51, 0x74, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x43, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x15, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x71, 0x74, 0x79, 0x22, 0x6c, 0x0a, 0x16, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x72, 0x65, 0x65,
	0x62, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x72, 0x65, 0x65,
	0x62, 0x69, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x71, 0x74, 0x79, 0x32, 0xee, 0x02, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x45, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x73, 0x68, 0x6f, 0x66, 0x66, 0x61, 0x2f, 0x62,
	0x63, 0x67, 0x64, 0x76, 0x2d, 0x6b, 0x75, 0x6e, 0x63, 0x69, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_promotion_proto_rawDescOnce sync.Once
	file_promotion_proto_rawDescData = file_promotion_proto_rawDesc
)

func file_promotion_proto_rawDescGZIP() []byte {
	file_promotion_proto_rawDescOnce.Do(func() {
		file_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(file_promotion_proto_rawDescData)
	})
	return file_promotion_proto_rawDescData
}

var file_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_promotion_proto_goTypes = []interface{}{
	(*Promotion)(nil),                // 0: Promotion
	(*CreatePromotionRequest)(nil),   // 1: CreatePromotionRequest
	(*CreatePromotionResponse)(nil),  // 2: CreatePromotionResponse
	(*GetAllPromotionsResponse)(nil), // 3: GetAllPromotionsResponse
	(*UpdatePromotionRequest)(nil),   // 4: UpdatePromotionRequest
	(*UpdatePromotionResponse)(nil),  // 5: UpdatePromotionResponse
	(*DeletePromotionRequest)(nil),   // 6: DeletePromotionRequest
	(*DeletePromotionResponse)(nil),  // 7: DeletePromotionResponse
	(*CheckPromotionRequest)(nil),    // 8: CheckPromotionRequest
	(*CheckPromotionResponse)(nil),   // 9: CheckPromotionResponse
	(*empty.Empty)(nil),              // 10: google.protobuf.Empty
}
var file_promotion_proto_depIdxs = []int32{
	0,  // 0: CreatePromotionResponse.promotion:type_name -> Promotion
	0,  // 1: GetAllPromotionsResponse.promotions:type_name -> Promotion
	0,  // 2: UpdatePromotionResponse.promotion:type_name -> Promotion
	1,  // 3: PromotionService.CreatePromotion:input_type -> CreatePromotionRequest
	10, // 4: PromotionService.GetAllPromotions:input_type -> google.protobuf.Empty
	4,  // 5: PromotionService.UpdatePromotion:input_type -> UpdatePromotionRequest
	6,  // 6: PromotionService.DeletePromotion:input_type -> DeletePromotionRequest
	8,  // 7: PromotionService.CheckPromotion:input_type -> CheckPromotionRequest
	2,  // 8: PromotionService.CreatePromotion:output_type -> CreatePromotionResponse
	3,  // 9: PromotionService.GetAllPromotions:output_type -> GetAllPromotionsResponse
	5,  // 10: PromotionService.UpdatePromotion:output_type -> UpdatePromotionResponse
	7,  // 11: PromotionService.DeletePromotion:output_type -> DeletePromotionResponse
	9,  // 12: PromotionService.CheckPromotion:output_type -> CheckPromotionResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_promotion_proto_init() }
func file_promotion_proto_init() {
	if File_promotion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_promotion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Promotion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePromotionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePromotionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPromotionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePromotionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePromotionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePromotionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePromotionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPromotionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promotion_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPromotionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_promotion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_promotion_proto_goTypes,
		DependencyIndexes: file_promotion_proto_depIdxs,
		MessageInfos:      file_promotion_proto_msgTypes,
	}.Build()
	File_promotion_proto = out.File
	file_promotion_proto_rawDesc = nil
	file_promotion_proto_goTypes = nil
	file_promotion_proto_depIdxs = nil
}
